# Generated by Django 6.0.2 on 2026-03-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobapplication_applied_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='applicant_name',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(default='Unknown', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(default='Unknown', upload_to='resumes/'),
            preserve_default=False,
        ),
    ]
